# _config.yml
# opções básicas
theme: jekyll-theme-minimal
title: polythropos
author: Pedro Alves de Lima
email: plima@me.com
description: só mais uma página estática no GitHub
twitter_username: ipedrolima
github_username: pelima

# configurações da build
markdown: kramdown

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap